### ISSUE TITLE
Unsupported CACAO signature type

### ISSUE THREAD

**Issue by dabuchera** [pradel/stacks-ceramic-demo#3]
Hi Léo

Thanks a lot for this excellent prototype.
Could you add which versions of `@ceramicnetwork/cli @composedb/cli` you used?
Everything was working perfectly except for the following error, which could be coming from similar stuff as [here](https://forum.ceramic.network/t/solved-unsupported-cacao-signature-type/118/4)

![image](https://user-images.githubusercontent.com/53481997/224171886-34f12e8d-74db-4843-bb41-3a4ccc6647ab.png)

**Comment by pradel** [comment]
Thanks for trying it out! For now you will need to run the node on my branch or wait for the Stacks pull request to be merged by ceramic https://github.com/ceramicnetwork/js-ceramic/pull/2649 :)

**Comment by dabuchera** [comment]
Nice. Is working perfectly. Ty

**Comment by dabuchera** [comment]
Pull request resolved for js-ceramic
https://github.com/ceramicnetwork/js-ceramic/pull/2649

**Comment by dabuchera** [comment]
No need to build the branch from source
Since version @ceramicnetwork/cli@2.29.0 integrated
Just run as described: `pnpm install -g @ceramicnetwork/cli @composedb/cli`
