### ISSUE TITLE
Question Relay __generated__ folder

### ISSUE THREAD

**Issue by dabuchera** [pradel/stacks-ceramic-demo#4]
Hi Léo

Quick question
How did you generate a typescript version of the 4 graphql files for relay `src/__generated__/relay/`
With relay-compiler-language-typescript?

Thanks

**Comment by pradel** [comment]
It's using the [`relay-compiler` ](https://www.npmjs.com/package/relay-compiler) package provided by relay

**Comment by pradel** [comment]
Config is here https://github.com/pradel/stacks-ceramic-demo/blob/main/relay.config.js

**Comment by dabuchera** [comment]
Ah nice, I see. And then `pnpm run relay` runs when starting the whole thing

**Comment by dabuchera** [comment]
For reference:
https://relay.dev/docs/guides/compiler/
